### ISSUE TITLE
This starter can't be set up without php installed locally

### ISSUE THREAD

**Issue by javaDeveloperKid** [jolicode/docker-starter#245]
I was looking for some PHP docker starter template and found this one. However to set up the docker environment I need to have php installed locally because of castor.  It doesn't make sense :)

**Comment by lyrixx** [comment]
This is not an issue for us. We are PHP developer so it does not make sens to not have PHP installed 😅

**Comment by pyrech** [comment]
First, we previously used python to drive our docker infrastructure because we didn't want to write the long docker-compose commands by hand. Makefile and equivalent were not an option because bash is still an hell to write and read for most people. 

Time passed and we were fed up with python ecosystem, breaking stuff quite often. As lyrixx said, we are mostly PHP developer so we largely prefer to:
- install php and the dependencies with Composer (❤️) than python and its messy ecosystem;
- write our task in PHP.

Finally, docker-starter's first objective is to allow us to run our web apps (complete apps with many services, not just php) locally without pain. So yes, we now require to have PHP installed locally but that's not an issue for us. We understand it's not acceptable for everyone, but as we are first users of this project, it's mostly adapted to our practices. If it helps other people, that's really cool (and that's why we open sourced the repository some times ago). If not, sorry to hear but nobody is forced to use it 🙂. Cheers!

**Comment by pyrech** [comment]
For the record, Castor can now be installed without PHP : https://castor.jolicode.com/getting-started/installation/#without-php

Enjoy :slightly_smiling_face:
